import React from "react";
import Head from "next/head";

import { getProviders, useSession, signIn, signOut } from "next-auth/react";

import logo from "../../assets/image/logo.svg";

import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/router";

const Login = ({ providers }) => {
  const { data: session } = useSession();
  const router = useRouter();
  if (session) {
    router.push("/");
  }
  console.log(providers);
  console.log(session);
  return (
    <>
      <Head>
        <title>Đăng Nhập </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="" />
      </Head>
      <div className="relative w-full h-screen bg-[rgba(18,18,18,.8)] z-50">
        <div className="absolute top-[50%] translate-x-[-50%]  translate-y-[-50%] left-[50%] ">
          <div className="w-[34rem]  bg-[#ffffff] text-white text-center rounded-md overflow-hidden">
            <Link href="/">
              <div className="!w-[190] h-[60] bg-primary relative ">
                <Image
                  src={logo}
                  width="180"
                  height="80"
                  className=" cursor-pointer bg-primary rounded-md pr-10"
                />
              </div>
            </Link>

            <div className="p-8 pb-12">
              <div className="text-black mt-3 text-xl font-bold ">
                ĐĂNG NHẬP
              </div>
              <div className="text-black text-base mb-10 ">
                Đăng nhập để bắt đầu!{" "}
              </div>

              <button
                onClick={() => signIn(providers.facebook.id)}
                className="w-[100%] bg-[#1871ed] mt-5 py-2 rounded-md flex justify-center items-center hover:bg-[#074cad] ease-linear duration-100 "
              >
                <i className="bx bxl-facebook text-2xl mr-3"></i> Đăng Nhập Với
                Facebook
              </button>
              <button
                onClick={() => signIn(providers.google.id)}
                className="w-[100%] bg-[#e7334b] mt-5 py-2 rounded-md flex justify-center items-center hover:bg-[#db2f46] ease-linear duration-100 "
              >
                <i className="bx bxl-google text-2xl mr-3"></i> Đăng Nhập Với
                Google
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

Login.getInitialProps = async (context) => {
  return {
    providers: await getProviders(context),
  };
};

export default Login;
