import Head from "next/head";
import Image from "next/image";
import { Row, Col } from "antd";
import HeroSlider from "../components/HeroSlider";
import movieApi from "../api/movieApi";
import { useEffect, useState } from "react";
import SectionCategory from "../components/Home/SectionCategory";
import TopTrending from "../components/Home/TopTrending";

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await movieApi.getAll(0);
  //banner
  const Banners = res.data.data.recommendItems.filter(
    (item) =>
      item.bannerProportion === null && item.homeSectionType === "BANNER"
  );

  //newSeriesMovie
  const newSeriesMovie = res.data.data.recommendItems.filter(
    (item) =>
      item.homeSectionId === 80388 && item.homeSectionType === "SINGLE_ALBUM"
  );
  const dataSeriesMovie = newSeriesMovie[0].recommendContentVOList.slice(0, 8);

  //newtrendNew
  const newtrendNew = res.data.data.recommendItems.filter(
    (item) =>
      item.homeSectionId === 80375 && item.homeSectionType === "SINGLE_ALBUM"
  );
  const dataTrendNew = newtrendNew[0].recommendContentVOList.slice(0, 8);

  //newFilm
  const newFilm = res.data.data.recommendItems.filter(
    (item) =>
      item.homeSectionId === 80377 && item.homeSectionType === "SINGLE_ALBUM"
  );
  const dataCinemaCollection = newFilm[0].recommendContentVOList.slice(0, 6);

  //dataTV
  const dataTVPost = {
    size: 50,
    params: "TV",
    area: "",
    category: "",
    year: "",
    subtitles: "",
    order: "up",
  };
  const resDataTV = await movieApi.getSearch(dataTVPost);
  const dataTV = resDataTV.data.data.searchResults.slice(0, 6);

  //dataMoive

  const dataMoviePost = {
    size: 50,
    params: "MOVIE",
    area: "",
    category: "",
    year: "",
    subtitles: "",
    order: "up",
  };
  const resDataMovie = await movieApi.getSearch(dataMoviePost);
  const dataMovie = resDataMovie.data.data.searchResults.slice(0, 6);

  // Pass data to the page via props
  return {
    props: {
      Banners,
      dataTV,
      dataMovie,
      dataSeriesMovie,
      dataTrendNew,
      dataCinemaCollection,
    },
  };
}

export default function Home({
  dataTV,
  Banners,
  dataMovie,
  dataSeriesMovie,
  dataTrendNew,
  dataCinemaCollection,
}) {
  const [Top10V1, setTop10V1] = useState([]);
  const [Top10V2, setTop10V2] = useState([]);

  useEffect(() => {
    const getAll02 = async () => {
      const res = await movieApi.getAll(2);

      const newTop10V1 = res.data.data.recommendItems.filter(
        (item) =>
          item.homeSectionId === 80393 &&
          item.homeSectionType === "SINGLE_ALBUM"
      );
      console.log(newTop10V1);
      // setTop10V1(newTop10V1[0].recommendContentVOList.slice(0, 10));

      const newTop10V2 = res.data.data.recommendItems.filter(
        (item) =>
          item.homeSectionId === 80391 &&
          item.homeSectionType === "SINGLE_ALBUM"
      );
      // setTop10V2(newTop10V2[0].recommendContentVOList.slice(0, 10));
    };
    getAll02();
  }, []);

  return (
    <>
      <Head>
        <title>Xem Phim Online Miễn Phí - Movie102 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="" />
      </Head>
      <>
        <HeroSlider data={Banners[0].recommendContentVOList} />

        <div className="box_shadow shadow-4xl z-[19] relative ">
          <div className="home_container z-[20] relative bg-bg_black min-h-[15rem] mx-auto max-w-[1200px] pt-[50px]">
            <div className="flex-2 grid grid-cols-3 gap-[50px]">
              <div className="col-span-2">
                <SectionCategory
                  title="Phim Bộ Hàn Hot Nhất"
                  data={dataSeriesMovie}
                />
                <SectionCategory
                  title="Xu Hướng Mới Nhất"
                  data={dataTrendNew}
                />
              </div>

              <div className="">
                <TopTrending data={Top10V1} title="BẢNG XẾP HẠNG" />
                <TopTrending data={Top10V2} title="PHIM HOẠT HÌNH" />
              </div>
            </div>
            <SectionCategory
              title="Tuyển Tập Điện Ảnh"
              data={dataCinemaCollection}
              className="!grid-cols-6"
            />
            <SectionCategory
              title="Phim Bộ"
              data={dataTV}
              className="!grid-cols-6"
            />
            <SectionCategory
              title="Phim Lẻ"
              data={dataMovie}
              className="!grid-cols-6"
            />
          </div>
        </div>
      </>
    </>
  );
}
